version: 2

sources:
  - name: chainwalkers
    schema: prod
    database: chainwalkers
    tables:
      - name: terra2_blocks
      - name: terra2_txs
  - name: crosschain_silver
    schema: silver
    database: crosschain
    tables:
      - name: address_labels
      - name: number_sequence
      - name: labels_combined
  - name: bronze
    schema: bronze
    database: terra
    tables:
      - name: lq_blocks
      - name: lq_txs
      - name: classic_validator_voting_power
      - name: classic_terra_api
      - name: classic_terra_sink_645110886
      - name: classic_rest_proxy_1507016047
      - name: terra_balances
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "TERRA_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "TERRA" }}
    tables:
      - name: blocks
      - name: transactions
  - name: shared
    database: crosschain
    schema: bronze
    tables:
      - name: legacy_prices
      - name: prod_address_label_sink_291098491
      - name: prod_address_tag_sync_1480319581
      - name: prod_nft_metadata_uploads_1828572827
      - name: prod_data_science_uploads_1748940988
  - name: crosschain_core
    database: crosschain
    schema: core
    tables:
      - name: dim_date_hours
  - name: github_actions
    database: terra
    schema: github_actions
    tables:
      - name: workflows